# Thanks for downloading Shop! #
# If you enjoy the plugin, let me know! I would love to hear from you! #

usePermissions: false

# If you want to use virtual money, install the plugin Vault and set ‘useVault to true #
# For itemCurrency, see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html #

Economy:
   useVault: false
   itemCurrency (non-vault): EMERALD
   displayName: Rupee(s)
   currencyToStartWith: 0


# Allowable percent difference in durabilities of items in shops #
maxDurabilityMargin: 5

