# Thanks for downloading Shop! #
#——————————————————————————————#

AUTO-UPDATE: true

usePermissions: false

# If you want to use virtual money, install the plugin Vault and set ‘useVault to true #
# For itemCurrency, see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html #

Economy:
   useVault: false
   itemCurrency (non-vault): EMERALD
   displayName: Rupee
   currencyToStartWith: 0


# Allowable percent difference in durabilities of items in shops #
maxDurabilityMargin: 5

